apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mogdb-ha-rolebinding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: mogdb-ha-role
subjects:
  - kind: ServiceAccount
    name: mogdb-ha
    namespace: mogha
