apiVersion: apps/v1
kind: Deployment
metadata:
  name: mogdb-ha
  namespace: mogha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogdb-ha
  template:
    metadata:
      labels:
        app: mogdb-ha
    spec:
      containers:
        - name: mogha
          image: mogha:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          command:
            - /usr/local/bin/mogdb-ha
          ports:
            - containerPort: 6544
              name: api
          readinessProbe:
            httpGet:
              path: "/"
              port: 6544
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/"
              port: 6544
              scheme: HTTP
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 60
      serviceAccountName: $(SA_NAME)
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: $(IMAGE_PULL_SECRET_NAME)
