# permissions for end users to view opengaussclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mogdbcluster-viewer-role
rules:
- apiGroups:
  - opengauss.enmotech.io
  resources:
  - opengaussclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opengauss.enmotech.io
  resources:
  - opengaussclusters/status
  verbs:
  - get
