# permissions for end users to edit opengaussclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mogdbcluster-editor-role
rules:
- apiGroups:
  - opengauss.enmotech.io
  resources:
  - opengaussclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opengauss.enmotech.io
  resources:
  - opengaussclusters/status
  verbs:
  - get
