apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  backup:
    auto:
      name: "auto"
      backupSchedules:
        full: "*/1 * * * *"
      storageProvider:
        rcloneStorage:
          name: s3-remote
          directory: backup
      backupType: basebackup
      backupFileHistoryLimit: 7
      failedJobsHistoryLimit: 7
      successfulJobsHistoryLimit: 7
    image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0