apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: mogdb-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogdb-multi-operator
  template:
    metadata:
      labels:
        app: mogdb-multi-operator
    spec:
      containers:
        - name: operator
          image: controller:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: $(NAMESPACE)
            - name: CONTROL_PLANE
              value: "true"
          command:
            - /usr/local/bin/multi-operator
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            periodSeconds: 10
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 20
            initialDelaySeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: false
      serviceAccountName: $(SA_NAME)
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: $(IMAGE_PULL_SECRET_NAME)
