apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}global-config
data:
  config.json: |
    {
      "operatorName": "",
      "imageNamePairs": [
        {"name": "RELATED_IMAGE_BACKUP", "image": "swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-command:v1.0.1"},
        {"name": "RELATED_IMAGE_RESTORE", "image": "swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-command:v1.0.1"}
      ],
      "haServices": ["http://127.0.0.1:8080"]
    }
