apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}mgo-config
  namespace: {{ .Values.namespace }}
data:
  rclone.conf: |
    [backup]
    type = s3
    provider = Minio
    env_auth = false
    access_key_id = root
    secret_access_key = root@123
    endpoint = http://10.1.193.125:9000
