apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namePrefix }}leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.namePrefix }}leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}controller-manager
  namespace: {{ .Values.namespace }}
