apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namePrefix }}manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}controller-manager
  namespace: {{ .Values.namespace }}
