
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.namePrefix }}manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbbackups/finalizers
  verbs:
  - update
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbrecoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbrecoveries/finalizers
  verbs:
  - update
- apiGroups:
  - mogdb.enmotech.io
  resources:
  - mogdbrecoveries/status
  verbs:
  - get
  - patch
  - update
