apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mogdb-ha-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters
    verbs:
      - get
      - list
      - watch
