apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mogdb-ha
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogdb-ha
  template:
    metadata:
      labels:
        app: mogdb-ha
    spec:
      serviceAccountName: mogdb-ha
      terminationGracePeriodSeconds: 10
      containers:
        - name: mogha
          image: mogha:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          command:
            - /usr/local/bin/mogdb-ha
          ports:
            - containerPort: 6544
              name: api
          readinessProbe:
            httpGet:
              path: "/"
              port: 6544
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/"
              port: 6544
              scheme: HTTP
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 60
      imagePullSecrets:
        - name: huawei-registry
