kind: Service
apiVersion: v1
metadata:
  name: mogdb-ha
  namespace: system
  labels:
    app: mogdb-ha
spec:
  ports:
    - name: api
      protocol: TCP
      port: 6544
      targetPort: 6544
  selector:
    app: mogdb-ha
  type: ClusterIP
  sessionAffinity: None
