---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "install.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "install.deployLables" . | indent 6 }}
      {{- include "install.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "install.deployLables" . | indent 8 }}
        {{- include "install.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "install.serviceAccountName" . }}
      containers:
        - name: apiserver
          image: {{ .Values.apiserverImages }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8444
              name: api
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: CRUNCHY_DEBUG
              value: 'true'
            - name: PORT
              value: '8444'
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MGO_OPERATOR_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DISABLE_TLS
              value: 'false'
            - name: ADD_OS_TRUSTSTORE
              value: 'false'
          volumeMounts:
            - mountPath: "/tmp"
              name: tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
      {{- include "install.imagePullSecrets" . | indent 6 }}