apiVersion: v1
stringData:
  permissions: "*"
  rolename: admin
kind: Secret
metadata:
  labels:
    {{- include "install.roleSecretLabels" . | indent 4 }}
    {{- include "install.labels" . | indent 4 }}
  name: {{ include "install.roleSecretName" . }}
type: Opaque