---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "install.serviceName" . }}
  labels:
    {{- include "install.serviceLabels" . | indent 4 }}
    {{- include "install.labels" . | indent 4 }}
spec:
  ports:
    - name: apiserver
      protocol: TCP
      port: 8444
      targetPort: 8444
      nodePort: {{ .Values.apiServerPort }}
  selector:
    {{- include "install.serviceSelectors" . | indent 4 }}
  type: NodePort
  sessionAffinity: None