apiVersion: mogdb.enmotech.io/v1
kind: MultiCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  dataCenters:
    - name: dc1
      namespace: mogdb-operator-system
      region: "dc1"
      dataCenterRole: primary
      kubeContextName: "data-plane1"
      dataCenterSpec:
        restore:
          restoreId: "001"
          dataSource:
            type: "time"
            backupType: dumpall
            clusterName: mogdb-cluster
            storageProvider:
              rcloneStorage:
                name: s3-remote
                directory: backup
            target: "2023-05-17T03:38:09.82"
          image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0
    - name: dc2
      namespace: mogdb-operator-system
      region: "dc2"
      dataCenterRole: standby
      kubeContextName: "data-plane2"
