kind: Service
apiVersion: v1
metadata:
  name: {{ include "install.serviceName" . }}
  labels:
    {{- include "install.labels" . | indent 4 }}
spec:
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.apiPort }}
      targetPort: {{ .Values.apiPort }}
  selector:
    {{- include "install.labels" . | indent 4 }}
  type: ClusterIP
  sessionAffinity: None
