apiVersion: v1
stringData:
  permissions: "*"
  rolename: admin
kind: Secret
metadata:
  labels:
    mgo-created-by: upgrade
    mgo-mgorole: "true"
    rolename: admin
    vendor: enmotech
  name: mgorole-admin
  namespace: {{ .Values.namespace }}
type: Opaque

