apiVersion: v1

kind: Service

metadata:

  name: prometheus

  namespace: monitoring

spec:

  selector:

    app: prometheus

  type: NodePort

  ports:

    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31042

    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 31044


