apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "install.managerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "install.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "install.labels" . | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "install.labels" . | indent 8 }}
    spec:
      securityContext:
        # runAsNonRoot: true
        runAsNonRoot: false
      containers:
      - command:
        - /usr/local/bin/mogdb-operator
        args:
        - --leader-elect
        env:
          - name: MOG_OPERATOR_NAMESPACE
            value: {{ .Release.Namespace }}
        image: {{ required ".Values.controllerImage is required" .Values.controllerImage | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- if .Values.resources }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ include "install.serviceAccountName" .}}
      terminationGracePeriodSeconds: 10
      {{- include "install.imagePullSecrets" . | nindent 6 }}
