
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleKind" . }}
metadata:
  name: {{ include "install.roleName" . }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/exec
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbbackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbbackups/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbbackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
