apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  labels:
    mogdb.enmotech.io/cluster: {{ .Values.clusterName }}
    name: {{ .Values.clusterName }}
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.nameSpace }}
spec:
  podSpec:
    backupVolumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.backupStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
    exporterImage: {{ .Values.images.exporterImage }}
    image: {{ .Values.images.mogdbImage }}
    imagePullPolicy: {{ .Values.images.pullPolicy }}
    initImage: {{ .Values.images.initImage }}
    serviceAccountName: {{ include "install.serviceAccountName" . }}
    {{- if .Values.resources }}
    resources:
    {{- toYaml .Values.resources | nindent 6 }}
    {{- end }}
    logVolumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.logStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.dataStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
  readPort: {{ .Values.readPort }}
  replicas: {{ .Values.replicaCount }}
  writePort: {{ .Values.writePort }}
  {{- if .Values.enableHa }}
  enableHa: true
  {{- end }}
  {{- if .Values.backup }}
  backup:
{{ toYaml .Values.backup | indent 4 }}
  {{- end }}
  {{- if .Values.restore }}
  restore:
{{ toYaml .Values.restore | indent 4 }}
  {{- end }}