apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  restore:
    restoreId: "001"
    dataSource:
      type: "object"
      backupType: basebackup
      clusterName: mogdb-cluster
      storageProvider:
        rcloneStorage:
          name: s3-remote
          directory: backup
      target: basebackup-2023-06-20-19-18-01.tar.gz
    image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0