apiVersion: v1

kind: Service

metadata:

  name: prometheus

  namespace: {{ .Values.namespace }}

spec:

  selector:

    app: prometheus

  type: NodePort

  ports:

    - protocol: TCP

      port: 9090

      targetPort: 9090

      nodePort: {{ .Values.prometheusNodeport }}

    - protocol: TCP

      port: 9093

      targetPort: 9093

      nodePort: {{ .Values.alertmanagerNodeport }}


