apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleBindingKind" . }}
metadata:
  name: {{ include "install.leaderElectionRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "install.roleKind" . }}
  name: {{ include "install.leaderElectionRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "install.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
