# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: mogdb-operator-system
spec:
  template:
    spec:
      containers:
        - name: operator
          image: controller:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTROL_PLANE
              value: "false"
          args:
            - "--leader-election"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi