apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  labels:
    mogdb.enmotech.io/cluster: {{ .Values.clusterName }}
    name: {{ .Values.clusterName }}
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.nameSpace }}
spec:
  podSpec:
    backupVolumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.backupStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
    exporterImage: {{ .Values.image.exporter.repository }}:{{ .Values.image.exporter.tag }}
    image: {{ .Values.image.mogdb.repository }}:{{ .Values.image.mogdb.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    initImage: {{ .Values.image.init.repository }}:{{ .Values.image.init.tag }}
    logVolumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.logStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.dataStorageSize }}
        storageClassName: {{ .Values.volume.storageClass }}
  readPort: {{ .Values.readPort }}
  replicas: {{ .Values.replicaCount }}
  writePort: {{ .Values.writePort }}
